### ISSUE TITLE
 Update CONTRIBUTING.md with Guidelines on Creating Issues, Writing Better Comments, and Submitting PRs

### ISSUE THREAD

**Issue by rishyym0927** [rishyym0927/Affinity_frontend#13]
We need to update the CONTRIBUTING.md file to provide clear instructions on how contributors can effectively participate in the project. The updated document should include the following details:

**1.  How to Create Issues:** 

- Explain the process of creating an issue, including how to properly describe the problem or feature request.
- Mention the importance of providing a clear, concise title and a detailed explanation of the issue.
- Encourage the use of templates if available and emphasize attaching any relevant screenshots, logs, or code snippets.

**2. Writing Better Comments for Issue Assignment:**

- Provide guidelines on how contributors should communicate when asking for issues to be assigned.
- Mention the need for detailing how they plan to approach and solve the issue.
- Request contributors to include thoughtful and constructive comments to make it easier for maintainers to understand their approach.

**3. How to Create Pull Requests (PRs):**

- Step-by-step instructions on how to submit a pull request, from forking the repo to making changes and submitting the PR.
- Explain the importance of maintaining a clean and organized commit history (squash or rebase commits if necessary).
- Highlight the need for clear commit messages that explain the changes made, and link the issue being resolved in the PR description.

**4. Time Limit for Assigned Issues:**

- Specify that once an issue is assigned, contributors will have 1-2 days to solve the issue and submit a PR.
- Mention that failure to meet the deadline may result in the issue being reassigned to someone else.

**These updates will help streamline the contribution process and ensure that all contributors are aligned on the best practices for creating issues, providing meaningful comments, and submitting clean pull requests.**

**Comment by kartikey369-ind** [comment]
Hello @rishyym0927 , I noticed the issue . I'd be happy to work on it if you could kindly assign it to me.

**Comment by kartikey369-ind** [comment]
Hello @rishyym0927 , I noticed the task regarding updating the contributors.md file and I believe it aligns well with my experience.

Objective: My goal is to enhance the contributors.md file to include relevant details of all contributors in an organized format, providing recognition and also making it easier to navigate.

Steps:

Gather Contributor Information: I will ensure each contributor’s name, GitHub profile link, and the details of their contributions are accurately included.
Formatting: I'll use markdown syntax to format the file, adding a clean and consistent layout. This may involve sections for profiles, images, and descriptions.
Sort by Contribution: Contributors will be sorted based on specific criteria, such as role or contribution type, for better readability.
Expected Outcome: A well-organized contributors.md file that acknowledges every contributor's effort while maintaining clarity for visitors of the repository.

I would be excited to work on this and contribute to the project. If you think I'm suitable for it, could you kindly assign me the issue? I'd greatly appreciate the opportunity.

**Comment by rishyym0927** [comment]
Hey @kartikey369-ind ,

I’ve already assigned an issue to you. Please complete that first before taking on another task.

**Comment by mahendra3399** [comment]
@rishyym0927  Can you assign me this issue

**Comment by rishyym0927** [comment]
Hey @mahendra3399,

You can work on this issue, but please make sure that next time when requesting an issue, you include a clear and detailed comment outlining your workflow.

Thanks!

**Comment by mahendra3399** [comment]
Thanks for assigning the issue @rishyym0927 

Here is the workflow I plan to follow:

How to Create Issues:
I will explain the process of creating an issue, including how to properly describe the problem or feature request.
I will mention the importance of providing a clear, concise title and a detailed explanation of the issue.
I will encourage the use of templates if available and emphasize attaching any relevant screenshots, logs, or code snippets.
Writing Better Comments for Issue Assignment:
I will provide guidelines on how contributors should communicate when asking for issues to be assigned.
I will mention the need for detailing how they plan to approach and solve the issue.
I will request contributors to include thoughtful and constructive comments to make it easier for maintainers to understand their approach.
How to Create Pull Requests (PRs):
I will provide step-by-step instructions on how to submit a pull request, from forking the repo to making changes and submitting the PR.
I will explain the importance of maintaining a clean and organized commit history (squash or rebase commits if necessary).
I will highlight the need for clear commit messages that explain the changes made, and link the issue being resolved in the PR description.
Time Limit for Assigned Issues:
I will specify that once an issue is assigned, contributors will have 1-2 days to solve the issue and submit a PR.
I will mention that failure to meet the deadline may result in the issue being reassigned to someone else.
I believe these updates will help streamline the contribution process and ensure that all contributors are aligned on the best practices for creating issues, providing meaningful comments, and submitting clean pull requests.

Kindly assign me this issue under Hacktoberfest 2024

**Comment by rishyym0927** [comment]
> Hey @mahendra3399,
> 
> You can work on this issue, but please make sure that next time when requesting an issue, you include a clear and detailed comment outlining your workflow.
> 
> Thanks!

Already Assigned
