### ISSUE TITLE
Integrate Role-Based Route Protection and redirect user to custom Denied Page for Unauthorized Access

### ISSUE THREAD

**Issue by Anshul-Sharma01** [rishyym0927/Affinity_frontend#15]
I would like to propose refactoring of the current route access logic by implementing a centralized RequireAuth component. This component will allow us to define role-based restrictions for specific routes and redirect unauthorized users to a denied page. Here’s what I plan to do:

- Create a RequireAuth component that checks if a user is logged in and has the appropriate role to access the route.
- Add a dedicated "Denied" page to notify users who don't have permission to access certain routes.
- Refactor the existing route protection logic
- Ensure unauthorized users are redirected to the /denied page instead of the landing page.

This enhancement will improve maintainability and provide a cleaner approach to route access control.

I want to work under this issue for hacktoberfest, please assign this issue to me.

**Comment by rishyym0927** [comment]
Hey, this is a great idea! However, we don't plan to implement role-based features in the project for now. We already have protected routing in place using context, so if you're interested in improving that, feel free to propose your workflow again with those adjustments. Let me know what you think!

**Comment by Anshul-Sharma01** [comment]
Okk then for now can I just make a denied page for inaccessible routes for a particular user and would see if i can improve your current implementation of the route protection.

**Comment by rishyym0927** [comment]
> Okk then for now can I just make a denied page for inaccessible routes for a particular user and would see if i can improve your current implementation of the route protection.

Absolutely, feel free to create a new issue along with your proposed workflow. I recommend focusing on one specific task at a time, as multiple changes will still count as a single pull request. By concentrating on smaller features and documenting each as a separate issue, you can effectively streamline your contributions.
