### ISSUE TITLE
Create a Denied Page for Inaccessible Routes

### ISSUE THREAD

**Issue by Anshul-Sharma01** [rishyym0927/Affinity_frontend#19]
I would like to add a dedicated "Denied" page that will be displayed when users attempt to access routes they are not authorized to view. This page will clearly inform users that they do not have the necessary permissions to access the requested route.

The proposed flow:

+ Users without the required access rights will be redirected to /denied when they attempt to access restricted routes.
+ The denied page will be a simple and informative component that explains the reason for the redirection.

This feature will improve user experience by providing feedback for unauthorized access instead of silently redirecting them elsewhere.

Please assign me this issue under Hacktoberfest

**Comment by rishyym0927** [comment]
Hi @Anshul-Sharma01 

This issue is assigned to you, add screenshots of your page when you create the pr and do not forget to link your issue in commit message.
