### ISSUE TITLE
Update README.md to clarify that environment variables are not required

### ISSUE THREAD

**Issue by rishyym0927** [rishyym0927/Affinity_frontend#2]
**The README.md file needs to be updated with the following information:**

Environment variables: Clarify that environment variables are not necessary to run the project. Users can proceed without setting them up.
Routing: Explain that users can use / to access different pages freely.
Data manipulation: Mention that users have complete freedom to manipulate the sample data according to their needs.

Feel free to improve and format the README file to make it more user-friendly and informative.

**Suggested improvements:**

Add a section under "Getting Started" or "Usage" for better clarity on how to navigate the project and manipulate data.
Consider adding examples or a small tutorial on how the sample data can be used and modified.

**Comment by AMANVISHWAKARMA27** [comment]
Hey @rishyym0927 , I would like to work on this issue. Kindly assign me this.

**Comment by codebydeep** [comment]
Hii, great to work with you on this issue. 
@rishyym0927

**Comment by rishyym0927** [comment]
**Issues will be assigned starting from October 1st on a first-come, first-served basis**. Before requesting an issue to be assigned, please provide a brief explanation of your approach and how you intend to resolve it. This will help streamline the process and ensure efficient collaboration

**Comment by rishyym0927** [comment]
Hi @AMANVISHWAKARMA27 

The issue is now assigned to you. Please proceed, and don't hesitate to reach out if you have any questions. Looking forward to your contribution!

**Comment by AMANVISHWAKARMA27** [comment]
@rishyym0927 Thanks . WIll respond asap.
