### ISSUE TITLE
Add Register Page Link on Login Page

### ISSUE THREAD

**Issue by M-ayank2005** [rishyym0927/Affinity_frontend#44]
Description
We need to add a link to the registration page on our login page. This will improve user experience by making it easier for new users to create an account without having to navigate away from the login page.
Objectives

Add a clearly visible link to the registration page on the login page
Ensure the link is styled consistently with our UI design
Implement the link in a way that's accessible and responsive

Tasks

 Decide on the exact wording for the link (e.g., "New user? Register here", "Create an account")
 Determine the best placement for the link on the login page
 Add the HTML for the link
 Style the link to match our UI design
 Ensure the link is keyboard-accessible
 Add appropriate aria labels for screen readers
 Test the link on various devices and screen sizes
 Update any relevant unit or integration tests
 Update user documentation to reflect this new feature

Technical Details

Add the following HTML to the login page, adjusting as necessary:
htmlCopy<p class="register-link">
  New user? <a href="/register" class="register-button">Create an account</a>
</p>

Add appropriate CSS to style the link, for example:
cssCopy.register-link {
  margin-top: 20px;
  text-align: center;
}

.register-button {
  color: #007bff;
  text-decoration: none;
  font-weight: bold;
}

.register-button:hover {
  text-decoration: underline;
}

Ensure the link uses the correct route for the registration page

Additional Considerations

Consider adding a brief explanation of the benefits of registering
Ensure the link doesn't distract from the main login form
Consider A/B testing different placements or wordings for the link
Ensure the change is consistent across all login instances (e.g., modal popups, standalone pages)

Acceptance Criteria

 The register link is visible and easily clickable on the login page
 Clicking the link successfully navigates to the registration page
 The link is styled consistently with our UI design
 The link is accessible via keyboard navigation
 The link has appropriate aria labels for screen readers
 The link and surrounding text are responsive and look good on all screen sizes

Labels
frontend, UX, enhancement

**Comment by rishyym0927** [comment]
assigned
