### ISSUE TITLE
Create a Custom 404 Page

### ISSUE THREAD

**Issue by rishyym0927** [rishyym0927/Affinity_frontend#6]
Description: The project requires a custom 404 error page to enhance user experience when navigating to non-existent routes. The page should:

- Display a friendly error message informing the user that the page was not found.
- Include a link to redirect users back to the homepage or a relevant section of the site.
- Ensure the design is consistent with the overall site theme and responsive across devices.

The goal is to provide a user-friendly and aesthetically pleasing experience when users encounter a 404 error.

**Comment by piyusss11** [comment]
okay working on that

**Comment by Sidharth-Singh10** [comment]
@piyusss11, please request the maintainers to assign the issue to you before opening a pull request (PR). Once assigned, you can proceed with the PR.

**Comment by piyusss11** [comment]
> @piyusss11, please request the maintainers to assign the issue to you before opening a pull request (PR). Once assigned, you can proceed with the PR.

my bad. I didn't know. this was my first time. Will take care in the future.

**Comment by pavithrakumar22** [comment]
hey @rishyym0927 i am very much intrested in this and very eager to make my first ever open source contribution so could u please assign this to me

**Comment by pavithrakumar22** [comment]
so my approcah will be as follows:
->I will be creating a notfound.jsx file.
->Use JSX to structure the content of your 404 page, including a clear error message, a brief explanation, and a link to the homepage or relevant section.
->Apply CSS styles to match your site's theme and make the page visually appealing.

**Comment by rishyym0927** [comment]
Thank you for sharing your approach! The issue is now assigned to you. Please proceed with your plan and make sure to submit your PR once completed. If you need any help along the way, feel free to ask!

**Comment by pavithrakumar22** [comment]
@rishyym0927 just a small doubt . Can I use lucide-react for the icons and tailwind css directly inside the jsx for the custom404 page?

**Comment by rishyym0927** [comment]
> @rishyym0927 just a small doubt . Can I use lucide-react for the icons and tailwind css directly inside the jsx for the custom404 page?

We already have react-icons package so you do not need to add other extra packages. You can use tailwind css directly.

**Comment by piyusss11** [comment]
Can i also work on this?
I have already created this before.
My approach is - 
-I will create a 404 error page using JSX.
-The page will feature an animated message using Framer Motion, where the text will move up and down in a slow loop.
-There will be a "Back to Home" button that navigates to the home route ("/").
-The UI will be kept simple and aligned with the website's color scheme, as users are unlikely to spend more than a few seconds -on this page. Overloading the design could negatively impact the user experience.
-The page will be responsive, optimized for both mobile devices and desktop screens.

![Screenshot (80)](https://github.com/user-attachments/assets/38af27fc-0986-4e61-9e5f-a05fc61a76bd)

**Comment by rishyym0927** [comment]
> Can i also work on this? I have already created this before. My approach is - -I will create a 404 error page using JSX. -The page will feature an animated message using Framer Motion, where the text will move up and down in a slow loop. -There will be a "Back to Home" button that navigates to the home route ("/"). -The UI will be kept simple and aligned with the website's color scheme, as users are unlikely to spend more than a few seconds -on this page. Overloading the design could negatively impact the user experience. -The page will be responsive, optimized for both mobile devices and desktop screens.
> 
> ![Screenshot (80)](https://private-user-images.githubusercontent.com/143982052/372914221-38af27fc-0986-4e61-9e5f-a05fc61a76bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MzY1NjEsIm5iZiI6MTcyNzkzNjI2MSwicGF0aCI6Ii8xNDM5ODIwNTIvMzcyOTE0MjIxLTM4YWYyN2ZjLTA5ODYtNGU2MS05ZTVmLWEwNWZjNjFhNzZiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QwNjE3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDViMjc0OGYyY2U3MGVlN2E3NDgwOWM2ZDA4OWU3YWQ2N2RlYWE2N2E5MzIyZTMxNDI0ODM3OTFlNmFiMmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XC1VTdhVoWoQIqvSxBM0D5rChJG_9mwO0231qhmnI5w)

assigned

**Comment by piyusss11** [comment]
> > Can i also work on this? I have already created this before. My approach is - -I will create a 404 error page using JSX. -The page will feature an animated message using Framer Motion, where the text will move up and down in a slow loop. -There will be a "Back to Home" button that navigates to the home route ("/"). -The UI will be kept simple and aligned with the website's color scheme, as users are unlikely to spend more than a few seconds -on this page. Overloading the design could negatively impact the user experience. -The page will be responsive, optimized for both mobile devices and desktop screens.
> > ![Screenshot (80)](https://private-user-images.githubusercontent.com/143982052/372914221-38af27fc-0986-4e61-9e5f-a05fc61a76bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MzY1NjEsIm5iZiI6MTcyNzkzNjI2MSwicGF0aCI6Ii8xNDM5ODIwNTIvMzcyOTE0MjIxLTM4YWYyN2ZjLTA5ODYtNGU2MS05ZTVmLWEwNWZjNjFhNzZiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QwNjE3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDViMjc0OGYyY2U3MGVlN2E3NDgwOWM2ZDA4OWU3YWQ2N2RlYWE2N2E5MzIyZTMxNDI0ODM3OTFlNmFiMmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XC1VTdhVoWoQIqvSxBM0D5rChJG_9mwO0231qhmnI5w)
> 
> assigned

Thanks
