### ISSUE TITLE
Add a Favicon to the Website

### ISSUE THREAD

**Issue by rishyym0927** [rishyym0927/Affinity_frontend#7]
**Description**: The website requires a favicon to improve its branding and user experience. The favicon should:

- Be designed in line with the project's overall theme and branding.
- Be visible in the browser tab, bookmarks, and other areas where favicons are displayed.
- Ensure compatibility across different browsers and devices.

Please create or upload the favicon, and ensure it is correctly linked in the HTML <head> section of the site.

**Comment by VanshChitransh** [comment]
@rishyym0927 Can i work on this issue.

**Comment by Sidharth-Singh10** [comment]
Hey @VanshChitransh , You can go ahead with your approach

**Comment by rishyym0927** [comment]
Hey @VanshChitransh are you working on this issue?

**Comment by VanshChitransh** [comment]
@rishyym0927 yes i am working on ti

**Comment by VanshChitransh** [comment]
@rishyym0927 hey can you unassign me from this issue.
